// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package anime_service

type Anime struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Author string `json:"author"`
}

type InputAnime struct {
	Title  string `json:"title"`
	Author string `json:"author"`
}
